### ISSUE TITLE
get  com.squareup.okhttp.Request.newBuilder()' on a null object reference ERROR

### ISSUE THREAD

**Issue by SamuelY** [dimitrovskif/SmartCache#3]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.squareup.okhttp.Request$Builder com.squareup.okhttp.Request.newBuilder()' on a null object reference
                                                       at dimitrovskif.smartcache.SmartCallFactory$SmartCallImpl.buildRequest(SmartCallFactory.java:200)
                                                       at dimitrovskif.smartcache.SmartCallFactory$SmartCallImpl.enqueue(SmartCallFactory.java:166)

**Comment by dimitrovskif** [comment]
Hi, I haven't maintained this lib for a long time. This may be a good opportunity to launch a new version with Retrofit 2.2 as a dependency and fix the issue you have.

**Comment by dimitrovskif** [comment]
Closed due to inactivity and no reproduction steps.
